### ISSUE TITLE
can not install petrofit package

### ISSUE THREAD

**Issue by danangsetyo5364** [PetroFit/petrofit#177]
Hallo currently I want to install `petrofit` package and I already use command `pip install petrofit` in CMD and this error message show up:

> (base) C:\Users\ASUS>python -m pip install petrofit
> 
> Defaulting to user installation because normal site-packages is not writeable
> Collecting petrofit
>   Using cached petrofit-0.4.1.tar.gz (4.0 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
> Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from petrofit) (1.23.5)
> Requirement already satisfied: astropy in c:\programdata\anaconda3\lib\site-packages (from petrofit) (5.1)
> Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from petrofit) (1.10.0)
> Requirement already satisfied: pyyaml in c:\programdata\anaconda3\lib\site-packages (from petrofit) (6.0)
> Collecting sklearn (from petrofit)
>   Using cached sklearn-0.0.post4.tar.gz (3.6 kB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [8 lines of output]
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "C:\Users\ASUS\AppData\Local\Temp\pip-install-y5mnwl16\sklearn_1aa93ce250d04430adc25652c4eae352\setup.py", line 10, in <module>
>           LONG_DESCRIPTION = f.read()
>         File "C:\ProgramData\anaconda3\lib\encodings\cp1252.py", line 23, in decode
>           return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>       UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 7: character maps to <undefined>
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

I already try to install `petrofit` via github and I still could not import this package

Any suggestion?

**Comment by robelgeda** [comment]
@danangsetyo5364 thank you for opening this ticket. It looks like the issue is with `sklearn` being installed on a windows machine. Quick things to try:

- `python -m pip install -U scikit-learn` and then try to install PF.
- Try to install the requirement file first `pip install -r /path/to/requirements.txt` where `requirements.txt` is located at the top directory of this repo. 

If both of these do not work, I have some questions that would help pin this down:
- Did installing `scikit-learn` work?
- What is your operating system? Are you using a virtual machine or WSL?
- Do you have conda installed (it seems like it but wanted to check)? If so, you can also use the environment file at the top directory. 

My best guess right now is that the encoding in scikit's setup file is not able to read the files it needs using windows encoders. 

Please let me know how it turns out and thanks again!

**Comment by danangsetyo5364** [comment]
Thanks a lot, it solved the problem! I think the main problem is I have not done this step :

> Try to install the requirement file first python -m pip install -r /path/to/requirements.txt where requirements.txt is located at the top directory of this repo.

As far as I know, there is none of the installation instructions say to do this. Maybe my suggestion is to add this steps in installation guide. Thank you very much!

**Comment by robelgeda** [comment]
I am glad that fixed things! 

I will keep this ticket open and will update the docs, thank you for your feedback!
